spring:
  application:
    name: qing-gateway
  redis:
    host: 47.113.189.237
    port: 6379
    password: cong0917
    timeout: 5000
    connect-timeout: 5000

server:
  port: 8101

logging:
  level:
    cn.qing.server: debug

qing:
  admin:
    infos:
      - url: localhost:9099
  server:
    load-balance: round_robin
    timeout-millis: 5000
    cache-refresh-interval-millis: 10000
  routes:
    - uri: traffic
      predicates: /test
      priority: 100
  httpclient:
    connectTimeout: 45000
    responseTimeout: 3000
    readerIdleTime: 3000
    writerIdleTime: 3000
    allIdleTime: 3000
    readTimeout: 3000
    writeTimeout: 3000
    wiretap: true
    keepAlive: false
    maxInMemorySize: 1 #1mb
    pool:
      type: ELASTIC
      name: proxy
      maxConnections: 16
      acquireTimeout: 45000
      maxIdleTime: 3000
    proxy:
      host:
      port:
      username:
      password:
      nonProxyHostsPattern:
    #    ssl:
    #      useInsecureTrustManager: true
    #      keyStoreType: PKCS12
    #      keyStorePath: classpath:keystore.p12
    #      keyStorePassword: 123456
    #      keyStoreProvider:
    #      keyPassword: 123456
    #      trustedX509Certificates:
    #      handshakeTimeout:
    #      closeNotifyFlushTimeout:
    #      closeNotifyReadTimeout:
    #      defaultConfigurationType:
    threadPool:
      prefix: qing-gateway
      selectCount: 1
      workerCount: 8
      daemon: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}